In [3]:
import pandas as pd
import numpy as np

In [8]:
mappings = pd.read_csv('../static/Module-Mappings.csv')
areas = pd.read_csv('../static/Country-Continent-Language.csv')

In [12]:
regions = []
countries = []
for uni in mappings['Partner University']:
    regions.append(areas[areas['University'] == uni]['Continent'].iloc[0])
    countries.append(areas[areas['University'] == uni]['Country'].iloc[0])

In [13]:
mappings['Country'] = countries
mappings['Continent'] = regions

In [15]:
mappings.to_csv('../static/Module-Mappings.csv',index=False)

In [32]:
def get_department(mod_code):
    output = ''
    numbers = '1234567890'
    for char in mod_code:
        if char not in numbers:
            output += char
        else:
            break
    return output

def get_level(mod_code):
    for char in mod_code:
        if char in '1234567890':
            return char

In [34]:
mod_codes1 = []
mod_codes2 = []
level = []
for mod in zip(mappings['NUS Module 1'],mappings['NUS Module 2']):
    try:
        mod_codes1.append(get_department(mod[0]))
    except:
        mod_codes1.append(np.nan)
        
    try:
        mod_codes2.append(get_department(mod[1]))
    except:
        mod_codes2.append(np.nan)
        
    try:
        level.append(get_level(mod[0]))
    except:
        level.append(np.nan)

In [37]:
mappings.to_csv('../static/Module-Mappings.csv',index=False)

In [38]:
mappings

,Faculty,Partner University,PU Module 1,PU Module 1 Title,PU Mod1 Credits,PU Module 2,PU Module 2 Title,PU Mod2 Credits,NUS Module 1,NUS Module 1 Title,NUS Mod1 Credits,NUS Module 2,NUS Module 2 Title,NUS Mod2 Credits,Pre Approved?,Country,Continent
0,School of Computing,Aalto University,CS--E4320,Cryptography and Data Security,5.0,NaN,NaN,NaN,CS2107,Introduction to Information Se,4.0,NaN,NaN,NaN,N,Finland,Europe
1,Faculty of Engineering,Aalto University,25C00200,Entrepreneurship and Innovation Management,3.0,NaN,NaN,NaN,MT4001,Innovation and Entrepreneurial,4.0,NaN,NaN,NaN,Y,Finland,Europe
2,Faculty of Engineering,Aalto University,KIE98.7011,Finnish 1A,2.0,NaN,NaN,NaN,EX1030,Exchange UEM,1.0,NaN,NaN,NaN,N,Finland,Europe
3,School of Computing,Aalto University,C3130,Information Security,5.0,NaN,NaN,NaN,CS2107,Introduction to Information Se,4.0,NaN,NaN,NaN,NaN,Finland,Europe
4,School of Computing,Aalto University,CS-C3130,Information Security,5.0,NaN,NaN,NaN,CS2107,Introduction to Information Se,4.0,NaN,NaN,NaN,N,Finland,Europe
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13026,NUS Business School,Zhejiang University,20120490,STRATEGIC MANAGEMENT IN BUSINESS,3.0,NaN,NaN,NaN,BSP3701,Strategic Management,4.0,NaN,NaN,NaN,Y,China,Asia
13027,NUS Business School,Zhejiang University,20120661,SUPPLY CHAIN MANAGEMENT,2.0,NaN,NaN,NaN,DOS3701,Supply Chain Management,4.0,NaN,NaN,NaN,Y,China,Asia
13028,NUS Business School,Zhejiang University,20190130,SUPPLY CHAIN MANAGEMENT,2.0,NaN,NaN,NaN,DOS3701,Supply Chain Management,4.0,NaN,NaN,NaN,Y,China,Asia
13029,NUS Business School,Zhejiang University,192340,THEORY AND IMPLEMENTATION OF INVESTMENT BANKS,3.0,NaN,NaN,NaN,FIN3761Y,Topics in Finance,4.0,NaN,NaN,NaN,Y,China,Asia
13030,School of Design & Environment,Zhejiang University,12120120,Urban Planning and Design,5.0,NaN,NaN,NaN,AR4101,Design 7,8.0,NaN,NaN,NaN,N,China,Asia